@apiUrl = http://localhost:80

###
# Get last price endpoint
GET {{apiUrl}}

###
# Get a price endpoint with timestamp
GET {{apiUrl}}?timestamp=2022-06-01T18:39:47Z

###
# Get average price endpoint with time range
GET {{apiUrl}}?from=2022-06-01T18:39:04Z&to=2023-06-01T18:47:47Z